version: '3.6'

services:
  api:
    stdin_open: true
    tty: true
    container_name: lolly_api
    build:
      context: ./api
      target: dev
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/opt/lolly_api
      - /opt/lolly_api/node_modules
    environment:
      PORT: 3000
      JWT_SECRET: 0cec9f23aec8d3b4e4cb24c5140dd78dade4b223defa219b4b5cf7e6f52fe40820d7f3934ef20977af0ee8e951196eacfe7f1ffb878790bee607d749f9133c48
      POSTGRES: postgres://postgres:postgres@lolly_postgres:5432/shop?poolMaxConnections=4&idleTimeout=900000

  postgres:
    restart: unless-stopped
    privileged: true
    build: './postgres'
    container_name: lolly_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    stdin_open: true
    tty: true
    build:
      context: ./web
      target: dev
      dockerfile: dockerfile
    container_name: lolly_web
    ports:
      - 8080:8080
    volumes:
      - ./web:/opt/lolly_web
      - /opt/lolly_web/node_modules

volumes:
  postgres: